- name: Configurer rsyslog pour surveiller les problèmes de sécurité (logs d'authentification, SSH)
  hosts: prod
  become: true
  vars_files:
    - ./vars/secret-variables.yaml

  tasks:
    - name: Lire les logs syslog
      command: tail -n 20 /var/log/syslog
      register: syslog_output

    - name: Afficher les logs syslog
      debug:
        var: syslog_output.stdout

    - name: Récupérer le fichier syslog complet
      fetch:
        src: /var/log/syslog
        dest: ./logs/{{ inventory_hostname }}/
        flat: yes


